
DELETE FROM news_tags;

DELETE FROM comments;

DELETE FROM news;

DELETE FROM tags;

DELETE FROM author;

ALTER TABLE author ALTER COLUMN id RESTART WITH 1;
ALTER TABLE tags ALTER COLUMN id RESTART WITH 1;
ALTER TABLE news ALTER COLUMN id RESTART WITH 1;
ALTER TABLE comments ALTER COLUMN id RESTART WITH 1;